version: '3'

services:
   
  # Nextcloud (DB + App + Webserver)
  
  db-nc:
    image: mariadb
    container_name: nextcloud-mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db-nc:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    env_file:
      - db-nc.env
    user: "mysql:mysql"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  app-nc:
    build: ./app-nc
    container_name: nextcloud-app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db-nc
    env_file:
      - db-nc.env
    depends_on:
      - db-nc
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

  web-nc:
    image: nginx:alpine
    container_name: nextcloud-nginx
    restart: always
    volumes:
      - ./web-nc/nginx.conf:/etc/nginx/nginx.conf
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=nc.network.local
    depends_on:
      - app-nc
    networks:
      - proxy-net
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M


 
  
  
  # phpMyAdmin
  
  app-pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_HOSTS=db-nc
      - VIRTUAL_HOST=pma.network.local
    depends_on:
      - db-nc
    networks:
      - proxy-net
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M


  
  # Certificate + Proxy
  
  certs:
    image: paulczar/omgwtfssl
    container_name: certificate
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=network.local
      - CA_SUBJECT=urale(tbz)@network.local
      - SSL_KEY=/certs/network.local.key
      - SSL_CSR=/certs/network.local.csr
      - SSL_CERT=/certs/network.local.crt
    networks:
      - proxy-net

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy-nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - ./proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-net
    depends_on:
      - certs
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 1536M

volumes:
  db-nc:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-net:
